trigger:
- main

pool:
  name: Default

variables:
  DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/StringExtensionsLib.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Lab4-ArtifactCI/Lab4Feed'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionsLib.csproj'
    configuration: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet'

- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Lab4-ArtifactCI/Lab4Feed'
    allowPackageConflicts: true
