trigger:
- main

pool:
  name: Default

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/StringExtensionsLib.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/StringExtensionsLib.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionsLib.csproj'
    configuration: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Lab4-ArtifactCI/Lab4Feed'
